---
os: osx
osx_image: xcode10.2

install:
  - pip3 install testinfra ansible ansible-lint yamllint
  - mv tests/_ansible.cfg ./ansible.cfg
  - mv tests/_.ansible-lint ./.ansible-lint
  - ansible-galaxy install -r tests/requirements.yml

script:
  - yamllint .
  - ansible-lint .
  - ansible-playbook tests/prepare.yml
  - ansible-playbook tests/provision.yml
  - py.test tests/test.py
  - ls -hal /Users/travis
  - ls -hal /Users/travis/.ssh
