---
os: osx
osx_image: xcode10.2

install:
  - pip3 install testinfra ansible ansible-lint yamllint
  - mv tests/_ansible.cfg ./ansible.cfg
  - mv tests/_.ansible-lint ./.ansible-lint
  - ansible-galaxy install -r tests/requirements.yml

script:
  - yamllint .
  - ansible-lint .
  - ansible-playbook tests/prepare.yml -vv
  - ansible-playbook tests/provision.yml -u macosbox -vvv
  - py.test -v tests/test.py
  - sudo ls -hal /Users/macosbox
  - sudo ls -hal /Users/macosbox/.ssh
