---
# Tasks related to ssh-key management.

- name: Ensure user ssh directory is present.
  file:
    path: "{{ mb_ssh_dir }}"
    owner: "{{ mb_user }}"
    group: "{{ mb_group }}"
    mode: "{{ mb_ssh_dir_mode }}"
    state: directory

- name: Copy keys from controller to remote host.
  copy:
    src: "{{ key }}"
    dest: "{{ mb_ssh_dir }}"
    owner: "{{ mb_user }}"
    group: "{{ mb_group }}"
    mode: "{{ ((key | splitext)[1] == 'pub') | ternary(mb_ssh_public_key_mode, mb_ssh_private_key_mode) }}"
  loop: "{{ query('fileglob',  mb_ssh_local_keys_dir + '/*') }}"
  loop_control:
    loop_var: key
